### ISSUE TITLE
[protoc-gen-tonic] Minimal.rs: Tried to insert into file that doesn't exist.

### ISSUE THREAD

**Issue by muusbolla** [neoeinstein/protoc-gen-prost#10] opened 2022-06-02 20:49 UTC
Running any of the below commands all give the same error + exit code 1: "Minimal.rs: Tried to insert into file that doesn't exist."
protoc --tonic_out=. ./minimal.proto
protoc --prost-crate_out=. ./minimal.proto // actually gives "Cargo.toml: Tried to insert into file that doesn't exist."
protoc --prost-serde_out=. ./minimal.proto

The below commands work:
protoc --prost_out=. ./minimal.proto           // produces Minimal.rs file with proto declaration but no GRPC service, as expected
protoc --tonic_out=. --tonic_opt=no_client=true,no_server=true ./minimal.proto                       // generates nothing
protoc --go-grpc_out=. ./min.proto                // generates a go service as expected, just for example

Minimal proto that causes this issue:
```
syntax = "proto3";
package Minimal;
option go_package="test.minimal"

// The request message
message ExampleRequest {
  string name = 1;
}

// The response message
message ExampleReply {
  string message = 1;
}

// The service definition
service Example {
  // Declare one RPC
  rpc ExampleRpc (ExampleRequest) returns (ExampleReply) {}
}

```

OS: Ubuntu 20.04 LTS

protoc --version: libprotoc 3.6.1

cargo install --list | grep protoc:
protoc-gen-prost v0.1.3:
    protoc-gen-prost
protoc-gen-prost-crate v0.1.5:
    protoc-gen-prost-crate
protoc-gen-prost-serde v0.1.0:
    protoc-gen-prost-serde
protoc-gen-tonic v0.1.0:
    protoc-gen-tonic

**Comment by neoeinstein** [comment] 2022-06-02 21:26
This is effectively a duplicate of #3. The tonic generator relies and builds on the artifacts provided by the prost generator. We could add an option not to append to that seed file, but the tonic generator isn't standalone and would rely on the generated prost files anyway.

**Comment by muusbolla** [comment] 2022-06-02 21:35
After running protoc --prost_out=. ./minimal.proto , the file Minimal.rs exists in the folder. Then I run protoc --tonic_out=. ./minimal.proto and I get the error "Minimal.rs: Tried to insert into file that doesn't exist."

**Comment by titanous** [comment] 2022-06-15 20:55
I pushed a workaround in #13.

**Closed** 2022-06-17 22:39 UTC
